[package]
name = "hs747/network"
description = "Extremely lightweight networking module. Features will be added continously."
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
